import os
import torch
import argparse
from datasets import load_dataset
from peft import LoraConfig, get_peft_model, TaskType
from transformers import (
    AutoModelForCausalLM,
    AutoTokenizer,
    TrainingArguments,
    DataCollatorForSeq2Seq
)
from trl import SFTTrainer

def parse_args():
    parser = argparse.ArgumentParser(description="Fine-tune open-source LLM for Historical Personas using LoRA")
    parser.add_argument("--model_path", type=str, default="Qwen/Qwen2.5-7B-Instruct", 
                        help="Base model path on HuggingFace or local directory")
    parser.add_argument("--dataset_path", type=str, required=True, 
                        help="Path to the JSONL dataset generated by dataset_curator.py (e.g. backend/munger_qa_dataset.jsonl)")
    parser.add_argument("--output_dir", type=str, default="./lora_adapter_output", 
                        help="Directory to save the trained LoRA adapters")
    parser.add_argument("--epochs", type=int, default=3, help="Number of training epochs")
    parser.add_argument("--batch_size", type=int, default=4, help="Batch size per device")
    parser.add_argument("--gradient_accumulation_steps", type=int, default=4, help="Gradient accumulation steps")
    parser.add_argument("--lr", type=float, default=2e-4, help="Learning rate")
    parser.add_argument("--lora_r", type=int, default=16, help="LoRA rank")
    parser.add_argument("--lora_alpha", type=int, default=32, help="LoRA alpha")
    
    return parser.parse_args()

def formatting_prompts_func(example):
    """
    Format Alpaca dataset style into Qwen/ChatML template conversations.
    """
    output_texts = []
    for i in range(len(example['instruction'])):
        # Construct chat message structure
        messages = [
            {"role": "system", "content": f"你现在是{example['meta'][i]['character']}的灵魂化身。请严格以他的立场、声音、口癖、心智模型和第一人称‘我’来回答问题，绝不准包含括号内的动作描写。"},
            {"role": "user", "content": example['instruction'][i]},
            {"role": "assistant", "content": example['output'][i]}
        ]
        output_texts.append(messages)
    return {"messages": output_texts}

def main():
    args = parse_args()
    
    print("=== Loading Tokenizer & Model ===")
    tokenizer = AutoTokenizer.from_pretrained(args.model_path, trust_remote_code=True)
    tokenizer.pad_token = tokenizer.eos_token
    
    # Load model with AutoModelForCausalLM
    # Enable bfloat16 for amp/A100/RTX 3090+ GPUs, fallback to float16 for older cards
    device_map = "auto"
    torch_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16
    
    model = AutoModelForCausalLM.from_pretrained(
        args.model_path,
        torch_dtype=torch_dtype,
        device_map=device_map,
        trust_remote_code=True
    )
    
    print("=== Loading and Formatting Dataset ===")
    if not os.path.exists(args.dataset_path):
        raise FileNotFoundError(f"Dataset not found at: {args.dataset_path}")
        
    dataset = load_dataset("json", data_files=args.dataset_path, split="train")
    
    # Shuffle dataset
    dataset = dataset.shuffle(seed=42)
    
    print(f"Loaded {len(dataset)} instruction examples.")
    
    # Set up LoRA Config
    peft_config = LoraConfig(
        task_type=TaskType.CAUSAL_LM,
        r=args.lora_r,
        lora_alpha=args.lora_alpha,
        lora_dropout=0.05,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
        bias="none"
    )
    
    print("=== Configuring Training Arguments ===")
    training_args = TrainingArguments(
        output_dir=args.output_dir,
        num_train_epochs=args.epochs,
        per_device_train_batch_size=args.batch_size,
        gradient_accumulation_steps=args.gradient_accumulation_steps,
        learning_rate=args.lr,
        logging_steps=10,
        save_strategy="epoch",
        evaluation_strategy="no",
        fp16=not torch.cuda.is_bf16_supported(),
        bf16=torch.cuda.is_bf16_supported(),
        optim="adamw_torch",
        report_to="none",  # Disable wandb reporting by default
        remove_unused_columns=False
    )
    
    print("=== Initializing SFTTrainer ===")
    # Format dataset using ChatML template helper
    formatted_dataset = dataset.map(
        formatting_prompts_func,
        batched=True,
        remove_columns=dataset.column_names
    )
    
    def apply_chat_template(example):
        return {
            "text": tokenizer.apply_chat_template(
                example["messages"],
                tokenize=False,
                add_generation_prompt=False
            )
        }
        
    train_dataset = formatted_dataset.map(apply_chat_template)
    
    trainer = SFTTrainer(
        model=model,
        train_dataset=train_dataset,
        peft_config=peft_config,
        dataset_text_field="text",
        max_seq_length=2048,
        tokenizer=tokenizer,
        args=training_args,
        data_collator=DataCollatorForSeq2Seq(tokenizer=tokenizer, pad_to_multiple_of=8, return_tensors="pt", padding=True)
    )
    
    print("=== Starting Model Fine-Tuning (Burn Tokens/Watts!) ===")
    trainer.train()
    
    print(f"=== Saving Fine-Tuned Adapters to {args.output_dir} ===")
    trainer.model.save_pretrained(args.output_dir)
    tokenizer.save_pretrained(args.output_dir)
    print("LoRA training successfully completed!")

if __name__ == "__main__":
    main()
